name: Build
on:
  push:
    branches:
      - main # the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - uses: actions/setup-java@v3
        with:
            distribution: 'adopt'
            java-version: '11.x'
      - uses: graalvm/setup-graalvm@v1
        with:
            version: '22.3.0'
            java-version: '11'
            components: 'native-image'
            github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Stop MySQL server
        run: sudo /etc/init.d/mysql stop
      - name: Install node.js packages
        run: npm ci
      - name: Grant mvn permissions
        run: chmod +x ./mvnw
      - name: Run backend test
        run: npm run ci:backend:test
      - name: Analyze code with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./mvnw -ntp initialize sonar:sonar
